services:
  api:
    build:
      context: .
      dockerfile: Dockerfile  # Uses the root Dockerfile for API
    ports:
      - "5001:8080"            # API listens on 8080 inside the container
    networks:
      - legalease-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  # Uses the separate Dockerfile for Frontend
    ports:
      - "3000:80"             # Blazor Server apps use port 80 internally
    networks:
      - legalease-net

networks:
  legalease-net:
    driver: bridge
