services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Host 5001 → Container 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - legalease-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Host 3000 → Container 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    networks:
      - legalease-net
