version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8080"  # Make sure this port is free
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - legalease-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Change this to another free port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    networks:
      - legalease-net

networks:
  legalease-net:
    driver: bridge
