services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - legalease-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    networks:
      - legalease-net

networks:
  legalease-net:
    driver: bridge
